version: 2

jobs:
  build:
    filters:
      branchs:
        only: master
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: unit-tests
          command: npm run test:unit
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy
          command: ./node-modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project=$FIREBASE_PROJECT
